name: Develop
on:
  push:
    branches:
      - 'develop'

jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deploy to AWS EC2 Instance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:dev

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOSTDEV }}
          username: ${{ secrets.USERNAMEDEV }}
          key: ${{ secrets.KEYDEV }}
          source: 'build/'
          target: '/home/ec2-user/front/'

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTDEV }}
          username: ${{ secrets.USERNAMEDEV }}
          key: ${{ secrets.KEYDEV }}
          script: /home/ec2-user/front/release.sh
